package com.leetcode.medium.array_strings;

import java.util.Arrays;

//TODO: used test cases generated by co-pilot
//prob #34 - first and last position of element in sorted array
public class FirstAndLastPositionOfElementInSortedArray_L34 {
    public static void main(String[] args) {
        //5,7,7,8,8,10  8
        //5,7,7,8,8,10  6
        //2,2,2,2,2     2
        //1,2,3,4,5     1
        System.out.println(Arrays.toString(searchRange(new int[]{1,2,3,4,5},1)));
    }

    //5,7,7,8,8,10      8
    //5,7,8,8,8,10      8
    //find values (i,j) in A such that A[i] < t && A[j] > t
    //m=!, A[m]==t? find i in left[] such that A[i] < t, find j in right[] such that A[j] > t return [i,j]
    //else if A[m]<t? return searchRange([m+1,end])
    //else return searchRange([start,m-1])
    public static int[] searchRange(int[] A, int t) {
        int tarIdx = targetIdx(A,0,A.length-1,t);
        System.out.println("target found at idx = "+tarIdx);
        int leftIdx,rightIdx;
        if(tarIdx==-1)return new int[]{-1,-1};
        else {
            //find lIdx in [0,tarIdx-1] such that A[idx] < t
            leftIdx = (tarIdx == 0) ? 0 : leftIndex(A,0,tarIdx-1,t);
            //if(leftIdx == -1)leftIdx = 0;
            //find rIdx in [tarIdx+1,A.length-1] such that A[rIdx] > t
            rightIdx = (tarIdx == A.length-1) ? A.length-1 : rightIndex(A,tarIdx+1,A.length-1,t);
            //if(rightIdx == -1)rightIdx=A.length-1;
        }
        //leftIdx != -1 ?
        if(rightIdx == -1)rightIdx = tarIdx;
        if(leftIdx == -1)leftIdx = tarIdx;
        return new int[]{leftIdx,rightIdx};
    }

    public static int targetIdx(int[] A,int start,int end,int t) {
        if(end-start <=0) {
            return A[start]==t ? start : -1;
        }
        int mid = start + (end-start)/2;
        if(A[mid] == t)return mid;
        else if(A[mid] > t)return targetIdx(A,start,mid-1,t);
        else return targetIdx(A,mid+1,end,t);
    }

    //5,7,7,8,8     8
    //2,2   2
    public static int leftIndex(int[] A,int start,int end,int t) {
        if(end-start <=0) {
            return A[end]==t ? end : -1;
        }
        int mid = start + (end-start)/2;
        if(A[mid]==t) {
            //A[mid-1] == t
            if(mid-1 >= start && A[mid-1]==t)return leftIndex(A,0,mid-1,t);
            //A[mid-1] < t
            else return mid;
        }
        return leftIndex(A,mid+1,end,t);
    }

    //8,10  8
    //2,2,2,2,2 - start=3, end=4, t=2
    //mid-1 >= start
    public static int rightIndex(int[] A,int start,int end,int t) {
        if(end-start <=0) {
            return A[start]==t ? start : -1;
        }
        int mid = start + (end-start)/2;
        if(A[mid]==t) {
            //A[mid+1] == t
            if(mid+1 <= end && A[mid+1]==t)return rightIndex(A,mid+1,end,t);
            //A[mid+1] > t
            else return mid;
        }
        return rightIndex(A,start,mid-1,t);
    }
}
